# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # test against latest update of each major Java version:
        java: [ 8, 11, 17, 21, 25 ]
    name: Build with Java ${{ matrix.java }}
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package

  deploy:
    name: Deploy with Java 8
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Needed to commit changes
    timeout-minutes: 30
    steps:
      - id: checkout
        name: Checkout sources
        uses: actions/checkout@v4
      - id: setup_jdk
        name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          java-package: jdk
          cache: maven
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - id: publish_artifacts
        name: Publish Artifacts
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            --activate-profiles enable-sign-artifacts \
            deploy
      - id: extract_version
        name: Extract Version
        if: ${{ !contains(env.curr_version,'SNAPSHOT') }}
        run: |
          #------------------------------------------------------
          # getting current version no from pom.xml
          #------------------------------------------------------               
          curr_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.- ' read -r -a tokens <<< ${curr_version}
          curr_year=${tokens[0]}
          curr_month=${tokens[1]}
          curr_build=${tokens[2]}
          echo curr_version: ${curr_version}
          # make version available to the next steps
          echo "curr_version=${curr_version}" >> $GITHUB_ENV
          #------------------------------------------------------
      - id: create_tag
        name: Create Tag
        if: ${{ !contains(env.curr_version,'SNAPSHOT') }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${curr_version}
          git push origin ${curr_version}
      - id: create-release
        name: Create Release
        if: ${{ !contains(env.curr_version,'SNAPSHOT') }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.curr_version }}
          files: |
            target/*.jar
            LICENSE
